import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom/client';
import './styles.css';

type WhaleWallet = { id:string; wallet_address:string; normalized_address:string; chain:string; label:string|null; wallet_type:string; notes:string|null; enabled:boolean; alert_threshold_usd:string; watch_priority:number; confidence_weighting:string; copy_trade_enabled:boolean; do_not_copy:boolean; last_seen_at:string|null; tags:string[]; sectors_of_interest:string[]; created_at:string; updated_at:string; };
type WalletMovement = { id:string; wallet_id:string; chain:string; transaction_hash:string; movement_type:string; token_symbol:string; token_contract:string|null; token_amount:string|null; estimated_usd_value:string|null; protocol:string|null; transaction_time:string; alert_threshold_crossed:boolean; data_quality_score:number; manual_review_required:boolean; raw_api_payload:Record<string, unknown>; };
type AgentAlert = { id:string; wallet_id:string|null; wallet_movement_id:string|null; alert_type:string; severity:string; title:string; message:string; data_quality_score:number; manual_review_required:boolean; decision_snapshot:Record<string, unknown>; status:string; analyst_notes:string|null; candidate_decision:string; created_at:string; acknowledged_at:string|null; };
type WalletSummary = { total_wallets:number; enabled_wallets:number; do_not_copy_wallets:number; movement_count:number; manual_review_movements:number; };
type PollingSummary = { provider:string; checked_wallets:number; eligible_wallets:number; fetched_movements:number; created_movements:number; skipped_duplicates:number; skipped_reason:string|null; provider_errors:number; paper_trading_only:boolean; };
type SignalOutcome = { id:string; wallet_movement_id:string; wallet_id:string; chain:string; token_symbol:string; horizon:string; provider:string; baseline_price:string|null; outcome_price:string|null; price_change_pct:string|null; direction:string; signal_result:string; measured_at:string; due_at:string; data_quality_score:number; paper_trading_only:boolean; raw_price_payload:Record<string, unknown>; created_at:string; updated_at:string; };
type SignalOutcomeSummary = { total_outcomes:number; favorable_outcomes:number; unfavorable_outcomes:number; neutral_outcomes:number; needs_review_outcomes:number; };
type SignalOutcomeRunSummary = { provider:string; checked_movements:number; created_outcomes:number; skipped_existing:number; checked_due_outcomes:number; skipped_not_due:number; provider_errors:number; paper_trading_only:boolean; };
type WalletPerformance = { wallet_id:string; label:string|null; normalized_address:string; chain:string; wallet_type:string; watch_priority:number; total_outcomes:number; favorable_outcomes:number; unfavorable_outcomes:number; neutral_outcomes:number; needs_review_outcomes:number; win_rate_pct:string; avg_return_pct:string; avg_data_quality_score:string; confidence_score:string; last_outcome_at:string|null; paper_trading_only:boolean; };
type TokenMapping = { id:string; chain:string; token_symbol:string; token_contract:string|null; provider:string; provider_token_id:string; source:string; confidence_score:number; notes:string|null; enabled:boolean; created_at:string; updated_at:string; };
type WalletImportSummary = { imported:number; skipped_duplicates:number; failed:number; wallet_ids:string[]; paper_trading_only:boolean; };
type MovementEnrichmentSummary = { provider:string; checked_movements:number; enriched_movements:number; skipped_unmapped:number; provider_errors:number; paper_trading_only:boolean; };

const API_BASE_URL = import.meta.env.VITE_BACKEND_BASE_URL ?? 'http://127.0.0.1:8000';
const walletTypes = ['Unknown','Whale','Smart Money','VC/Fund','Exchange','Market Maker','Influencer Wallet','Developer Wallet','Suspicious','Do Not Copy'];
const movementTypes = ['DEX buy','DEX sell','CEX deposit','CEX withdrawal','Wallet-to-wallet transfer','Bridge movement','Stablecoin accumulation','Stablecoin deployment','New token position','Position increase','Position reduction','Full exit'];
const emptySummary: WalletSummary = { total_wallets:0, enabled_wallets:0, do_not_copy_wallets:0, movement_count:0, manual_review_movements:0 };
const emptyOutcomeSummary: SignalOutcomeSummary = { total_outcomes:0, favorable_outcomes:0, unfavorable_outcomes:0, neutral_outcomes:0, needs_review_outcomes:0 };

function splitList(value:string){ return value.split(',').map((item)=>item.trim()).filter(Boolean); }
function formatUsd(value:string|number|null){ if(value === null || value === '') return 'n/a'; const number = Number(value); if(Number.isNaN(number)) return String(value); return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(number); }
function dateForInput(){ const now = new Date(); now.setMinutes(now.getMinutes() - now.getTimezoneOffset()); return now.toISOString().slice(0,16); }
function walletName(wallet?: WhaleWallet){ return wallet?.label || wallet?.normalized_address || 'Unknown wallet'; }

function App(){
  const [wallets,setWallets] = useState<WhaleWallet[]>([]);
  const [movements,setMovements] = useState<WalletMovement[]>([]);
  const [alerts,setAlerts] = useState<AgentAlert[]>([]);
  const [outcomes,setOutcomes] = useState<SignalOutcome[]>([]);
  const [performance,setPerformance] = useState<WalletPerformance[]>([]);
  const [tokenMappings,setTokenMappings] = useState<TokenMapping[]>([]);
  const [summary,setSummary] = useState<WalletSummary>(emptySummary);
  const [outcomeSummary,setOutcomeSummary] = useState<SignalOutcomeSummary>(emptyOutcomeSummary);
  const [loading,setLoading] = useState(true);
  const [saving,setSaving] = useState(false);
  const [movementSaving,setMovementSaving] = useState(false);
  const [message,setMessage] = useState('');
  const [error,setError] = useState('');
  const [chainFilter,setChainFilter] = useState('');
  const [movementFilter,setMovementFilter] = useState<'all'|'review'|'alerts'>('all');
  const [alertFilter,setAlertFilter] = useState<'open'|'all'|'review'>('open');
  const [polling,setPolling] = useState<PollingSummary|null>(null);
  const [outcomeRun,setOutcomeRun] = useState<SignalOutcomeRunSummary|null>(null);
  const [enrichmentRun,setEnrichmentRun] = useState<MovementEnrichmentSummary|null>(null);
  const [outcomeFilter,setOutcomeFilter] = useState<'all'|'favorable'|'unfavorable'|'review'>('all');
  const [performanceFilter,setPerformanceFilter] = useState<'all'|'mock'|'coingecko_public'>('all');
  const [form,setForm] = useState({ wallet_address:'', chain:'ethereum', label:'', wallet_type:'Unknown', alert_threshold_usd:'100000', watch_priority:'3', confidence_weighting:'1.00', copy_trade_enabled:false, do_not_copy:false, tags:'', sectors_of_interest:'', notes:'' });
  const [editId,setEditId] = useState('');
  const [editForm,setEditForm] = useState({ label:'', wallet_type:'Unknown', alert_threshold_usd:'100000', watch_priority:'3', confidence_weighting:'1.00', copy_trade_enabled:false, do_not_copy:false, tags:'', sectors_of_interest:'', notes:'', enabled:true });
  const [movementForm,setMovementForm] = useState({ wallet_id:'', movement_type:'DEX buy', token_symbol:'', token_contract:'', token_amount:'', estimated_usd_value:'', transaction_hash:'', protocol:'', transaction_time:dateForInput(), data_quality_score:'75' });
  const [importText,setImportText] = useState('[{"wallet_address":"0x...","chain":"ethereum","label":"Research wallet","wallet_type":"Whale","tags":["seed"]}]');
  const [tokenForm,setTokenForm] = useState({ chain:'ethereum', token_symbol:'ETH', token_contract:'', provider:'coingecko_public', provider_token_id:'ethereum', confidence_score:'90', notes:'' });

  const filteredWallets = useMemo(()=> chainFilter ? wallets.filter((wallet)=>wallet.chain === chainFilter) : wallets, [chainFilter,wallets]);
  const filteredMovements = useMemo(()=> movementFilter === 'review' ? movements.filter((m)=>m.manual_review_required) : movementFilter === 'alerts' ? movements.filter((m)=>m.alert_threshold_crossed) : movements, [movementFilter,movements]);
  const filteredAlerts = useMemo(()=> alertFilter === 'open' ? alerts.filter((a)=>!a.acknowledged_at) : alertFilter === 'review' ? alerts.filter((a)=>a.manual_review_required) : alerts, [alertFilter,alerts]);
  const filteredOutcomes = useMemo(()=> outcomeFilter === 'favorable' ? outcomes.filter((o)=>o.signal_result === 'favorable') : outcomeFilter === 'unfavorable' ? outcomes.filter((o)=>o.signal_result === 'unfavorable') : outcomeFilter === 'review' ? outcomes.filter((o)=>o.signal_result === 'needs_review') : outcomes, [outcomeFilter,outcomes]);

  async function api<T>(path:string, options?:RequestInit):Promise<T>{
    const response = await fetch(`${API_BASE_URL}${path}`, { headers:{'Content-Type':'application/json', ...(options?.headers ?? {})}, ...options });
    if(!response.ok){ let detail = `${response.status} ${response.statusText}`; try{ const body = await response.json(); detail = body.detail ?? detail; }catch{} throw new Error(detail); }
    return response.json();
  }
  async function loadData(){
    setLoading(true); setError('');
    try{
      const alertPath = alertFilter === 'open' ? '/agent-alerts?acknowledged=false&limit=100' : '/agent-alerts?limit=100';
      const performancePath = performanceFilter === 'all' ? '/wallet-performance?limit=100' : `/wallet-performance?provider=${performanceFilter}&limit=100`;
      const [walletData,movementData,summaryData,alertData,outcomeData,outcomeSummaryData,performanceData,tokenMappingData] = await Promise.all([api<WhaleWallet[]>('/wallets?limit=250'), api<WalletMovement[]>('/wallet-movements?limit=100'), api<WalletSummary>('/wallets/summary'), api<AgentAlert[]>(alertPath), api<SignalOutcome[]>('/signal-outcomes?limit=100'), api<SignalOutcomeSummary>('/signal-outcomes/summary'), api<WalletPerformance[]>(performancePath), api<TokenMapping[]>('/token-mappings?limit=100')]);
      setWallets(walletData); setMovements(movementData); setSummary(summaryData); setAlerts(alertData); setOutcomes(outcomeData); setOutcomeSummary(outcomeSummaryData); setPerformance(performanceData); setTokenMappings(tokenMappingData);
      setMovementForm((current)=>({...current, wallet_id: current.wallet_id || walletData[0]?.id || ''}));
    }catch(err){ setError(err instanceof Error ? err.message : 'Failed to load wallet intelligence'); }
    finally{ setLoading(false); }
  }
  useEffect(()=>{ loadData(); }, [performanceFilter]);

  function startEdit(wallet:WhaleWallet){
    setEditId(wallet.id);
    setEditForm({ label:wallet.label ?? '', wallet_type:wallet.wallet_type, alert_threshold_usd:String(wallet.alert_threshold_usd), watch_priority:String(wallet.watch_priority), confidence_weighting:String(wallet.confidence_weighting), copy_trade_enabled:wallet.copy_trade_enabled, do_not_copy:wallet.do_not_copy, tags:wallet.tags.join(', '), sectors_of_interest:wallet.sectors_of_interest.join(', '), notes:wallet.notes ?? '', enabled:wallet.enabled });
  }
  async function submitWallet(event:FormEvent<HTMLFormElement>){ event.preventDefault(); setSaving(true); setError(''); setMessage(''); try{ await api<WhaleWallet>('/wallets',{method:'POST',body:JSON.stringify({ wallet_address:form.wallet_address, chain:form.chain.trim().toLowerCase(), label:form.label || null, wallet_type:form.do_not_copy ? 'Do Not Copy' : form.wallet_type, notes:form.notes || null, alert_threshold_usd:form.alert_threshold_usd, watch_priority:Number(form.watch_priority), confidence_weighting:form.confidence_weighting, copy_trade_enabled:form.do_not_copy ? false : form.copy_trade_enabled, do_not_copy:form.do_not_copy, tags:splitList(form.tags), sectors_of_interest:splitList(form.sectors_of_interest) })}); setMessage('Wallet added. Research and paper-trading only.'); setForm((c)=>({...c,wallet_address:'',label:'',tags:'',sectors_of_interest:'',notes:'',copy_trade_enabled:false,do_not_copy:false})); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to save wallet'); }finally{ setSaving(false); } }
  async function submitEdit(event:FormEvent<HTMLFormElement>){ event.preventDefault(); if(!editId) return; setSaving(true); setError(''); setMessage(''); try{ await api<WhaleWallet>(`/wallets/${editId}`,{method:'PATCH',body:JSON.stringify({ label:editForm.label || null, wallet_type:editForm.do_not_copy ? 'Do Not Copy' : editForm.wallet_type, notes:editForm.notes || null, enabled:editForm.enabled, alert_threshold_usd:editForm.alert_threshold_usd, watch_priority:Number(editForm.watch_priority), confidence_weighting:editForm.confidence_weighting, copy_trade_enabled:editForm.do_not_copy ? false : editForm.copy_trade_enabled, do_not_copy:editForm.do_not_copy, tags:splitList(editForm.tags), sectors_of_interest:splitList(editForm.sectors_of_interest) })}); setMessage('Wallet updated.'); setEditId(''); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to update wallet'); }finally{ setSaving(false); } }
  async function submitMovement(event:FormEvent<HTMLFormElement>){ event.preventDefault(); const wallet = wallets.find((item)=>item.id === movementForm.wallet_id); if(!wallet){ setError('Select a watched wallet before adding a movement.'); return; } setMovementSaving(true); setError(''); setMessage(''); try{ await api<WalletMovement>('/wallet-movements',{method:'POST',body:JSON.stringify({ wallet_id:movementForm.wallet_id, chain:wallet.chain, transaction_hash:movementForm.transaction_hash, movement_type:movementForm.movement_type, token_symbol:movementForm.token_symbol, token_contract:movementForm.token_contract || null, token_amount:movementForm.token_amount || null, estimated_usd_value:movementForm.estimated_usd_value || null, protocol:movementForm.protocol || null, transaction_time:new Date(movementForm.transaction_time).toISOString(), data_quality_score:Number(movementForm.data_quality_score), raw_api_payload:{source:'manual_stage1_entry',paper_trading_only:true} })}); setMessage('Movement stored. Threshold crossings create review alerts only.'); setMovementForm((c)=>({...c,token_symbol:'',token_contract:'',token_amount:'',estimated_usd_value:'',transaction_hash:'',protocol:'',transaction_time:dateForInput()})); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to save movement'); }finally{ setMovementSaving(false); } }
  async function toggleWallet(wallet:WhaleWallet){ setError(''); setMessage(''); try{ await api<WhaleWallet>(`/wallets/${wallet.id}/enabled?enabled=${!wallet.enabled}`,{method:'PATCH'}); setMessage(`${walletName(wallet)} ${wallet.enabled ? 'disabled' : 'enabled'}.`); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to update wallet'); } }
  async function acknowledgeAlert(alert:AgentAlert){ setError(''); setMessage(''); try{ await api<AgentAlert>(`/agent-alerts/${alert.id}/acknowledge`,{method:'PATCH'}); setMessage('Alert acknowledged.'); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to acknowledge alert'); } }
  async function runPolling(provider:'dry_run'|'mock'|'etherscan_readonly' = 'dry_run'){ setError(''); setMessage(''); try{ const result = await api<PollingSummary>(`/wallet-polling/run-once?provider=${provider}`,{method:'POST'}); setPolling(result); setMessage(`Polling ${result.provider} checked ${result.checked_wallets} wallets, fetched ${result.fetched_movements}, created ${result.created_movements}.`); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to run polling skeleton'); } }
  async function runOutcomes(mode:'mock-all'|'mock-due'|'coingecko-due' = 'mock-all'){ setError(''); setMessage(''); try{ const path = mode === 'mock-all' ? '/signal-outcomes/run-once?provider=mock' : mode === 'mock-due' ? '/signal-outcomes/run-due?provider=mock' : '/signal-outcomes/run-due?provider=coingecko_public'; const result = await api<SignalOutcomeRunSummary>(path,{method:'POST'}); setOutcomeRun(result); setMessage(`Signal outcomes ${result.provider} checked ${result.checked_movements} movements, due ${result.checked_due_outcomes}, created ${result.created_outcomes}, existing ${result.skipped_existing}.`); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to run signal outcomes'); } }
  async function submitImport(event:FormEvent<HTMLFormElement>){ event.preventDefault(); setError(''); setMessage(''); try{ const parsed = JSON.parse(importText); const walletsToImport = Array.isArray(parsed) ? parsed : parsed.wallets; const result = await api<WalletImportSummary>('/wallets/import',{method:'POST',body:JSON.stringify({wallets:walletsToImport})}); setMessage(`Wallet import complete: ${result.imported} imported, ${result.skipped_duplicates} duplicates, ${result.failed} failed.`); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to import wallets'); } }
  async function submitTokenMapping(event:FormEvent<HTMLFormElement>){ event.preventDefault(); setError(''); setMessage(''); try{ await api<TokenMapping>('/token-mappings',{method:'POST',body:JSON.stringify({ chain:tokenForm.chain, token_symbol:tokenForm.token_symbol, token_contract:tokenForm.token_contract || null, provider:tokenForm.provider, provider_token_id:tokenForm.provider_token_id, confidence_score:Number(tokenForm.confidence_score), notes:tokenForm.notes || null, source:'manual_ui', enabled:true })}); setMessage('Token mapping saved.'); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to save token mapping'); } }
  async function runEnrichment(){ setError(''); setMessage(''); try{ const result = await api<MovementEnrichmentSummary>('/movement-enrichment/run-once?provider=coingecko_public',{method:'POST'}); setEnrichmentRun(result); setMessage(`Enrichment checked ${result.checked_movements}, enriched ${result.enriched_movements}, unmapped ${result.skipped_unmapped}.`); await loadData(); }catch(err){ setError(err instanceof Error ? err.message : 'Failed to enrich movements'); } }

  return <main className="app-shell">
    <section className="hero panel"><div><p className="eyebrow">Stage 2 · Wallets, Movements, Outcomes</p><h1>Wallet-led intelligence console</h1><p>Add watched wallets, store movements, review alerts and validate whether signals worked after 15m, 1h, 4h, 24h and 7d. V1 remains research and paper-trading only.</p></div><button className="ghost-button" onClick={loadData} disabled={loading}>{loading ? 'Refreshing…' : 'Refresh'}</button></section>
    <section className="stats-grid"><Stat label="Total wallets" value={summary.total_wallets}/><Stat label="Enabled" value={summary.enabled_wallets}/><Stat label="Movements" value={summary.movement_count}/><Stat label="Outcomes" value={outcomeSummary.total_outcomes}/><Stat label="Favorable" value={outcomeSummary.favorable_outcomes}/><Stat label="Unfavorable" value={outcomeSummary.unfavorable_outcomes}/></section>
    {error && <div className="notice error">{error}</div>}{message && <div className="notice success">{message}</div>}

    <section className="panel wallet-list"><div className="list-header"><div><p className="eyebrow">Wallet performance ranking</p><h2>{performance.length} ranked</h2><p className="muted">Ranks wallets by confidence-adjusted signal outcomes. This is research only, not trading advice.</p></div><label className="compact-label">Provider<select value={performanceFilter} onChange={(e)=>setPerformanceFilter(e.target.value as 'all'|'mock'|'coingecko_public')}><option value="all">All</option><option value="mock">Mock</option><option value="coingecko_public">CoinGecko public</option></select></label></div>{performance.length===0 ? <p className="muted">No ranked wallets yet. Create signal outcomes first.</p> : <div className="cards">{performance.map((item,index)=><article className="wallet-card movement-card" key={item.wallet_id}><div className="wallet-card-top"><div><h3>#{index+1} · {item.label || item.normalized_address}</h3><p className="address">{item.normalized_address}</p></div><span className={Number(item.confidence_score) >= 55 ? 'badge enabled' : Number(item.confidence_score) < 45 ? 'badge alert' : 'badge disabled'}>Score {Number(item.confidence_score).toFixed(1)}</span></div><div className="wallet-meta"><span>{item.chain}</span><span>{item.wallet_type}</span><span>{item.total_outcomes} outcomes</span><span>Win {Number(item.win_rate_pct).toFixed(1)}%</span><span>Avg {Number(item.avg_return_pct).toFixed(2)}%</span><span>Quality {Number(item.avg_data_quality_score).toFixed(0)}</span></div><div className="policy-row"><span>F {item.favorable_outcomes} / U {item.unfavorable_outcomes} / N {item.neutral_outcomes} / Review {item.needs_review_outcomes}</span><strong>{item.last_outcome_at ? `Last ${new Date(item.last_outcome_at).toLocaleString()}` : 'No outcomes yet'}</strong></div></article>)}</div>}</section>

    <section className="content-grid movements-grid"><form className="panel wallet-form" onSubmit={submitImport}><div><p className="eyebrow">Wallet import</p><h2>Bulk watchlist seed</h2><p className="muted">Paste a JSON array of wallet objects. Duplicates are skipped by chain/address.</p></div><label>Wallet JSON<textarea rows={8} value={importText} onChange={(e)=>setImportText(e.target.value)}/></label><button className="primary-button">Import wallets</button></form><form className="panel wallet-form" onSubmit={submitTokenMapping}><div><p className="eyebrow">Token identity</p><h2>Provider mapping</h2><p className="muted">Map wallet-led tokens to provider IDs for real price outcomes.</p></div><div className="form-row"><label>Chain<input value={tokenForm.chain} onChange={(e)=>setTokenForm({...tokenForm,chain:e.target.value.toLowerCase()})}/></label><label>Symbol<input value={tokenForm.token_symbol} onChange={(e)=>setTokenForm({...tokenForm,token_symbol:e.target.value.toUpperCase()})}/></label></div><label>Token contract<input value={tokenForm.token_contract} placeholder="optional" onChange={(e)=>setTokenForm({...tokenForm,token_contract:e.target.value})}/></label><div className="form-row"><label>Provider<select value={tokenForm.provider} onChange={(e)=>setTokenForm({...tokenForm,provider:e.target.value})}><option value="coingecko_public">CoinGecko public</option></select></label><label>Provider token ID<input required value={tokenForm.provider_token_id} placeholder="ethereum" onChange={(e)=>setTokenForm({...tokenForm,provider_token_id:e.target.value})}/></label></div><div className="form-row"><label>Confidence<input type="number" min="0" max="100" value={tokenForm.confidence_score} onChange={(e)=>setTokenForm({...tokenForm,confidence_score:e.target.value})}/></label><label>Notes<input value={tokenForm.notes} onChange={(e)=>setTokenForm({...tokenForm,notes:e.target.value})}/></label></div><button className="primary-button">Save token mapping</button>{tokenMappings.length>0 && <div className="tag-row">{tokenMappings.slice(0,8).map((mapping)=><span key={mapping.id}>{mapping.token_symbol} → {mapping.provider_token_id}</span>)}</div>}</form></section>

    <section className="content-grid"><WalletForm form={form} setForm={setForm} saving={saving} onSubmit={submitWallet}/><section className="panel wallet-list"><div className="list-header"><div><p className="eyebrow">Watched wallets</p><h2>{filteredWallets.length} shown</h2></div><label className="compact-label">Chain filter<input value={chainFilter} placeholder="all" onChange={(e)=>setChainFilter(e.target.value.trim().toLowerCase())}/></label></div>{filteredWallets.length === 0 ? <p className="muted">No wallets yet.</p> : <div className="cards">{filteredWallets.map((wallet)=><article className="wallet-card" key={wallet.id}><div className="wallet-card-top"><div><h3>{walletName(wallet)}</h3><p className="address">{wallet.normalized_address}</p></div><span className={wallet.enabled ? 'badge enabled' : 'badge disabled'}>{wallet.enabled ? 'Enabled' : 'Disabled'}</span></div><div className="wallet-meta"><span>{wallet.chain}</span><span>{wallet.wallet_type}</span><span>Priority {wallet.watch_priority}</span><span>{formatUsd(wallet.alert_threshold_usd)} alert</span></div>{(wallet.tags.length>0 || wallet.sectors_of_interest.length>0) && <div className="tag-row">{[...wallet.tags,...wallet.sectors_of_interest].map((tag)=><span key={tag}>{tag}</span>)}</div>}<div className="policy-row"><span>{wallet.copy_trade_enabled ? 'Paper copy-review allowed' : 'No copy-review'}</span>{wallet.do_not_copy && <strong>Do Not Copy</strong>}</div><div className="button-row"><button className="ghost-button" onClick={()=>startEdit(wallet)}>Edit</button><button className="ghost-button" onClick={()=>toggleWallet(wallet)}>{wallet.enabled ? 'Disable' : 'Enable'}</button></div></article>)}</div>}</section></section>

    {editId && <section className="panel edit-panel"><form className="wallet-form" onSubmit={submitEdit}><div className="list-header"><div><p className="eyebrow">Edit wallet</p><h2>{walletName(wallets.find((w)=>w.id===editId))}</h2></div><button type="button" className="ghost-button" onClick={()=>setEditId('')}>Cancel</button></div><WalletEditFields editForm={editForm} setEditForm={setEditForm}/><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Save wallet changes'}</button></form></section>}

    <section className="content-grid movements-grid"><MovementForm wallets={wallets} movementForm={movementForm} setMovementForm={setMovementForm} movementSaving={movementSaving} onSubmit={submitMovement}/><section className="panel wallet-list"><div className="list-header"><div><p className="eyebrow">Recent movements</p><h2>{filteredMovements.length} shown</h2></div><label className="compact-label">View<select value={movementFilter} onChange={(e)=>setMovementFilter(e.target.value as 'all'|'review'|'alerts')}><option value="all">All</option><option value="review">Manual review</option><option value="alerts">Large alerts</option></select></label></div>{filteredMovements.length===0 ? <p className="muted">No movements yet.</p> : <div className="cards">{filteredMovements.map((m)=>{ const wallet = wallets.find((w)=>w.id===m.wallet_id); return <article className="wallet-card movement-card" key={m.id}><div className="wallet-card-top"><div><h3>{m.movement_type} · {m.token_symbol}</h3><p className="address">{m.transaction_hash}</p></div><span className={m.alert_threshold_crossed ? 'badge alert' : 'badge enabled'}>{m.alert_threshold_crossed ? 'Large alert' : 'Stored'}</span></div><div className="wallet-meta"><span>{walletName(wallet)}</span><span>{m.chain}</span><span>{formatUsd(m.estimated_usd_value)}</span><span>Quality {m.data_quality_score}</span><span>{String(m.raw_api_payload?.source ?? 'manual')}</span></div><div className="policy-row"><span>{new Date(m.transaction_time).toLocaleString()}</span>{m.manual_review_required && <strong>Manual review</strong>}</div><details><summary>Movement source</summary><pre>{JSON.stringify(m.raw_api_payload,null,2)}</pre></details></article>; })}</div>}</section></section>

    <section className="content-grid movements-grid"><section className="panel wallet-form"><div><p className="eyebrow">Polling worker</p><h2>Dry-run skeleton</h2><p className="muted">Checks enabled, non-Do-Not-Copy wallets through a no-external-provider skeleton. Real providers come later without committing API keys.</p></div><div className="button-row"><button className="ghost-button" onClick={()=>runPolling('dry_run')}>Run dry-run</button><button className="ghost-button" onClick={()=>runPolling('etherscan_readonly')}>Run Etherscan read-only</button><button className="ghost-button" onClick={runEnrichment}>Enrich real movements</button><button className="primary-button" onClick={()=>runPolling('mock')}>Run mock ingestion</button></div>{polling && <div className="notice success">Provider {polling.provider}: checked {polling.checked_wallets}, fetched {polling.fetched_movements}, created {polling.created_movements}, duplicates {polling.skipped_duplicates}, provider errors {polling.provider_errors}. {polling.skipped_reason}</div>}{enrichmentRun && <div className="notice success">Enrichment {enrichmentRun.provider}: checked {enrichmentRun.checked_movements}, enriched {enrichmentRun.enriched_movements}, unmapped {enrichmentRun.skipped_unmapped}, errors {enrichmentRun.provider_errors}.</div>}</section><section className="panel wallet-list"><div className="list-header"><div><p className="eyebrow">Agent alerts</p><h2>{filteredAlerts.length} shown</h2></div><label className="compact-label">View<select value={alertFilter} onChange={(e)=>setAlertFilter(e.target.value as 'open'|'all'|'review')}><option value="open">Open</option><option value="review">Manual review</option><option value="all">All</option></select></label></div>{filteredAlerts.length===0 ? <p className="muted">No alerts for this filter.</p> : <div className="cards">{filteredAlerts.map((alert)=><article className="wallet-card movement-card" key={alert.id}><div className="wallet-card-top"><div><h3>{alert.title}</h3><p>{alert.message}</p></div><span className={alert.status === 'acknowledged' ? 'badge disabled' : 'badge alert'}>{alert.status}</span></div><div className="wallet-meta"><span>{alert.alert_type}</span><span>{alert.candidate_decision}</span><span>Quality {alert.data_quality_score}</span><span>{new Date(alert.created_at).toLocaleString()}</span></div><details><summary>Decision snapshot</summary><pre>{JSON.stringify(alert.decision_snapshot,null,2)}</pre></details>{!alert.acknowledged_at && <button className="ghost-button" onClick={()=>acknowledgeAlert(alert)}>Acknowledge</button>}</article>)}</div>}</section></section>

    <section className="content-grid movements-grid"><section className="panel wallet-form"><div><p className="eyebrow">Signal outcomes</p><h2>Price validation</h2><p className="muted">Creates research-only outcomes for 15m, 1h, 4h, 24h and 7d horizons. Use mock for deterministic validation or CoinGecko public for read-only wallet-led price checks.</p></div><div className="button-row"><button className="ghost-button" onClick={()=>runOutcomes('mock-due')}>Run due mock</button><button className="ghost-button" onClick={()=>runOutcomes('coingecko-due')}>Run due CoinGecko</button><button className="primary-button" onClick={()=>runOutcomes('mock-all')}>Run all mock</button></div>{outcomeRun && <div className="notice success">Provider {outcomeRun.provider}: checked {outcomeRun.checked_movements}, due {outcomeRun.checked_due_outcomes}, created {outcomeRun.created_outcomes}, existing {outcomeRun.skipped_existing}, not due {outcomeRun.skipped_not_due}, provider errors {outcomeRun.provider_errors}.</div>}<div className="wallet-meta"><span>Total {outcomeSummary.total_outcomes}</span><span>Favorable {outcomeSummary.favorable_outcomes}</span><span>Unfavorable {outcomeSummary.unfavorable_outcomes}</span><span>Review {outcomeSummary.needs_review_outcomes}</span></div></section><section className="panel wallet-list"><div className="list-header"><div><p className="eyebrow">Recent signal outcomes</p><h2>{filteredOutcomes.length} shown</h2></div><label className="compact-label">View<select value={outcomeFilter} onChange={(e)=>setOutcomeFilter(e.target.value as 'all'|'favorable'|'unfavorable'|'review')}><option value="all">All</option><option value="favorable">Favorable</option><option value="unfavorable">Unfavorable</option><option value="review">Needs review</option></select></label></div>{filteredOutcomes.length===0 ? <p className="muted">No signal outcomes yet. Store or mock-ingest movements, then run mock outcomes.</p> : <div className="cards">{filteredOutcomes.map((outcome)=><article className="wallet-card movement-card" key={outcome.id}><div className="wallet-card-top"><div><h3>{outcome.token_symbol} · {outcome.horizon}</h3><p>{outcome.provider} outcome · paper-trading only</p></div><span className={outcome.signal_result === 'favorable' ? 'badge enabled' : outcome.signal_result === 'unfavorable' ? 'badge alert' : 'badge disabled'}>{outcome.signal_result}</span></div><div className="wallet-meta"><span>{outcome.chain}</span><span>{outcome.direction}</span><span>{outcome.price_change_pct ? `${Number(outcome.price_change_pct).toFixed(2)}%` : 'n/a'}</span><span>Quality {outcome.data_quality_score}</span></div><div className="policy-row"><span>Base {outcome.baseline_price ?? 'n/a'} → Outcome {outcome.outcome_price ?? 'n/a'}</span><strong>Due {new Date(outcome.due_at).toLocaleString()}</strong></div><details><summary>Provider detail</summary><pre>{JSON.stringify(outcome.raw_price_payload,null,2)}</pre></details></article>)}</div>}</section></section>
  </main>;
}

function WalletForm({form,setForm,saving,onSubmit}:{form:any; setForm:(value:any)=>void; saving:boolean; onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){ return <form className="panel wallet-form" onSubmit={onSubmit}><div><p className="eyebrow">Add wallet</p><h2>Watchlist entry</h2></div><label>Wallet address<input required value={form.wallet_address} placeholder="0x…" onChange={(e)=>setForm({...form,wallet_address:e.target.value})}/></label><div className="form-row"><label>Chain<input required value={form.chain} onChange={(e)=>setForm({...form,chain:e.target.value})}/></label><label>Wallet type<select value={form.wallet_type} disabled={form.do_not_copy} onChange={(e)=>setForm({...form,wallet_type:e.target.value})}>{walletTypes.map((type)=><option key={type}>{type}</option>)}</select></label></div><label>Label<input value={form.label} placeholder="e.g. ETH early accumulator" onChange={(e)=>setForm({...form,label:e.target.value})}/></label><div className="form-row three"><label>Alert USD<input type="number" min="0" value={form.alert_threshold_usd} onChange={(e)=>setForm({...form,alert_threshold_usd:e.target.value})}/></label><label>Priority<select value={form.watch_priority} onChange={(e)=>setForm({...form,watch_priority:e.target.value})}><option value="1">1 · Highest</option><option value="2">2</option><option value="3">3 · Normal</option><option value="4">4</option><option value="5">5 · Low</option></select></label><label>Confidence<input type="number" min="0" max="5" step="0.1" value={form.confidence_weighting} onChange={(e)=>setForm({...form,confidence_weighting:e.target.value})}/></label></div><label>Tags<input value={form.tags} placeholder="comma separated" onChange={(e)=>setForm({...form,tags:e.target.value})}/></label><label>Sectors<input value={form.sectors_of_interest} placeholder="AI, DeFi" onChange={(e)=>setForm({...form,sectors_of_interest:e.target.value})}/></label><label>Notes<textarea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label><div className="checks"><label><input type="checkbox" checked={form.copy_trade_enabled} disabled={form.do_not_copy} onChange={(e)=>setForm({...form,copy_trade_enabled:e.target.checked})}/>Paper copy-review allowed</label><label><input type="checkbox" checked={form.do_not_copy} onChange={(e)=>setForm({...form,do_not_copy:e.target.checked,copy_trade_enabled:false})}/>Do Not Copy</label></div><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Add watched wallet'}</button></form>; }
function WalletEditFields({editForm,setEditForm}:{editForm:any; setEditForm:(value:any)=>void}){ return <><div className="form-row"><label>Label<input value={editForm.label} onChange={(e)=>setEditForm({...editForm,label:e.target.value})}/></label><label>Wallet type<select value={editForm.wallet_type} disabled={editForm.do_not_copy} onChange={(e)=>setEditForm({...editForm,wallet_type:e.target.value})}>{walletTypes.map((type)=><option key={type}>{type}</option>)}</select></label></div><div className="form-row three"><label>Alert USD<input type="number" min="0" value={editForm.alert_threshold_usd} onChange={(e)=>setEditForm({...editForm,alert_threshold_usd:e.target.value})}/></label><label>Priority<select value={editForm.watch_priority} onChange={(e)=>setEditForm({...editForm,watch_priority:e.target.value})}><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></label><label>Confidence<input type="number" min="0" max="5" step="0.1" value={editForm.confidence_weighting} onChange={(e)=>setEditForm({...editForm,confidence_weighting:e.target.value})}/></label></div><label>Tags<input value={editForm.tags} onChange={(e)=>setEditForm({...editForm,tags:e.target.value})}/></label><label>Sectors<input value={editForm.sectors_of_interest} onChange={(e)=>setEditForm({...editForm,sectors_of_interest:e.target.value})}/></label><label>Notes<textarea value={editForm.notes} onChange={(e)=>setEditForm({...editForm,notes:e.target.value})}/></label><div className="checks"><label><input type="checkbox" checked={editForm.enabled} onChange={(e)=>setEditForm({...editForm,enabled:e.target.checked})}/>Enabled</label><label><input type="checkbox" checked={editForm.copy_trade_enabled} disabled={editForm.do_not_copy} onChange={(e)=>setEditForm({...editForm,copy_trade_enabled:e.target.checked})}/>Paper copy-review allowed</label><label><input type="checkbox" checked={editForm.do_not_copy} onChange={(e)=>setEditForm({...editForm,do_not_copy:e.target.checked,copy_trade_enabled:false})}/>Do Not Copy</label></div></>; }
function MovementForm({wallets,movementForm,setMovementForm,movementSaving,onSubmit}:{wallets:WhaleWallet[]; movementForm:any; setMovementForm:(value:any)=>void; movementSaving:boolean; onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){ return <form className="panel wallet-form" onSubmit={onSubmit}><div><p className="eyebrow">Add movement</p><h2>Manual movement entry</h2><p className="muted">Use this smoke workflow until automated wallet polling is connected.</p></div><label>Wallet<select required value={movementForm.wallet_id} onChange={(e)=>setMovementForm({...movementForm,wallet_id:e.target.value})}><option value="">Select wallet</option>{wallets.map((wallet)=><option key={wallet.id} value={wallet.id}>{walletName(wallet)} · {wallet.chain}</option>)}</select></label><div className="form-row"><label>Movement type<select value={movementForm.movement_type} onChange={(e)=>setMovementForm({...movementForm,movement_type:e.target.value})}>{movementTypes.map((type)=><option key={type}>{type}</option>)}</select></label><label>Token symbol<input required value={movementForm.token_symbol} placeholder="ETH" onChange={(e)=>setMovementForm({...movementForm,token_symbol:e.target.value.toUpperCase()})}/></label></div><label>Transaction hash<input required value={movementForm.transaction_hash} placeholder="0x transaction hash" onChange={(e)=>setMovementForm({...movementForm,transaction_hash:e.target.value})}/></label><label>Token contract<input value={movementForm.token_contract} onChange={(e)=>setMovementForm({...movementForm,token_contract:e.target.value})}/></label><div className="form-row three"><label>Token amount<input type="number" step="any" value={movementForm.token_amount} onChange={(e)=>setMovementForm({...movementForm,token_amount:e.target.value})}/></label><label>Estimated USD<input type="number" min="0" step="any" value={movementForm.estimated_usd_value} onChange={(e)=>setMovementForm({...movementForm,estimated_usd_value:e.target.value})}/></label><label>Quality<input type="number" min="0" max="100" value={movementForm.data_quality_score} onChange={(e)=>setMovementForm({...movementForm,data_quality_score:e.target.value})}/></label></div><div className="form-row"><label>Protocol<input value={movementForm.protocol} onChange={(e)=>setMovementForm({...movementForm,protocol:e.target.value})}/></label><label>Transaction time<input type="datetime-local" value={movementForm.transaction_time} onChange={(e)=>setMovementForm({...movementForm,transaction_time:e.target.value})}/></label></div><button className="primary-button" disabled={movementSaving || wallets.length===0}>{movementSaving ? 'Saving…' : 'Store movement'}</button></form>; }
function Stat({label,value}:{label:string; value:number}){ return <div className="stat-card"><span>{label}</span><strong>{value}</strong></div>; }
ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(<React.StrictMode><App /></React.StrictMode>);
